[package]
edition.workspace = true
license.workspace = true
name = "runfile-runtime"
version.workspace = true

[dependencies]
runfile-discovery.workspace = true
runfile-env.workspace = true
runfile-lang.workspace = true
thiserror.workspace = true
which.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
