//! `run :generate <editor>` -- static task files for editors without an extension.
//!
//! Zed and JetBrains have no Runfile extension, so their task lists are files
//! generated from the catalog. VS Code has an extension that reads the catalog
//! live; the static form is for anyone who would rather not install it.
//!
//! A generated entry is recognised by its shape -- command `run`, label
//! `run <target>` -- so a later run replaces exactly those and leaves a
//! person's own entries alone. A file is rewritten with the indentation it
//! already uses; only a new file gets the default.

use std::path::Path;
use std::process::ExitCode;

use runfile_discovery::{Catalog, Origin};
use serde_json::{Map, Value, json};

pub const SUBS: &[&str] = &["zed", "jetbrains", "vscode"];
const USAGE: &str = "usage: run :generate <zed|jetbrains|vscode> [--include-global] [--stdout]";
const DEFAULT_INDENT: &str = "  ";

struct Options {
	/// Machine-wide targets are left out unless asked for: a task file is
	/// committed, and `~/.runfiles/` is one person's.
	include_global: bool,
	stdout: bool,
}

struct Entry {
	name: String,
	description: String,
	uses_args: bool,
}

pub fn dispatch(cat: &Catalog, args: &[String]) -> Result<ExitCode, String> {
	let Some(editor) = args.first() else {
		return Err(USAGE.into());
	};
	let mut opts = Options {
		include_global: false,
		stdout: false,
	};
	for a in &args[1..] {
		match a.as_str() {
			"--include-global" => opts.include_global = true,
			"--stdout" => opts.stdout = true,
			other => return Err(format!("unknown option `{other}`\n\n{USAGE}")),
		}
	}
	let entries = entries(cat, opts.include_global);
	let report = match editor.as_str() {
		"zed" => zed(&entries, &cat.root, &opts)?,
		"vscode" => vscode(&entries, &cat.root, &opts)?,
		"jetbrains" => jetbrains(&entries, &cat.root, &opts)?,
		other => {
			return Err(format!(
				"unknown editor `{other}`; expected one of: {}",
				SUBS.join(", ")
			));
		}
	};
	if !report.is_empty() {
		println!("{report}");
	}
	Ok(ExitCode::SUCCESS)
}

fn entries(cat: &Catalog, include_global: bool) -> Vec<Entry> {
	cat.targets
		.values()
		.filter(|t| include_global || t.origin != Origin::Global)
		.filter_map(|t| {
			let f = crate::list::facts(t);
			(!f.hidden).then(|| Entry {
				name: t.name.clone(),
				description: f.description,
				uses_args: f.uses_args,
			})
		})
		.collect()
}

// ---- recognising our own entries

fn label(name: &str) -> String {
	format!("run {name}")
}

/// Command `run`, label `run <target>`, and `<target>` among the arguments:
/// the shape every generated entry has, and that a hand-written one that
/// happens to call `run` is unlikely to.
fn ours(task: &Value) -> bool {
	if task["command"] != "run" {
		return false;
	}
	let Some(target) = task["label"].as_str().and_then(|l| l.strip_prefix("run ")) else {
		return false;
	};
	let args: Vec<&str> = task["args"]
		.as_array()
		.map(|a| a.iter().filter_map(Value::as_str).collect())
		.unwrap_or_default();
	matches!(args.as_slice(), ["--stdin-args", t, ..] | [t, ..] if *t == target)
}

#[derive(Default)]
struct Stats {
	added: usize,
	updated: usize,
	removed: usize,
	skipped: Vec<String>,
}

impl std::fmt::Display for Stats {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(
			f,
			"{} added, {} updated, {} removed",
			self.added, self.updated, self.removed
		)?;
		for s in &self.skipped {
			write!(f, "\n  skipped {s}: not generated by runfile")?;
		}
		Ok(())
	}
}

/// Replace our entries, keep everyone else's. An existing entry of ours keeps
/// any extra keys a person added to it; only the keys we generate are set.
fn merge(existing: &mut Vec<Value>, generated: Vec<Value>) -> Stats {
	let mut stats = Stats::default();
	let wanted: Vec<&str> = generated.iter().filter_map(|t| t["label"].as_str()).collect();
	let before = existing.len();
	existing.retain(|t| !ours(t) || t["label"].as_str().is_some_and(|l| wanted.contains(&l)));
	stats.removed = before - existing.len();
	for task in generated {
		let l = task["label"].as_str().unwrap_or_default().to_string();
		match existing.iter_mut().find(|t| t["label"] == l) {
			Some(Value::Object(slot)) => {
				if let Value::Object(fresh) = task {
					slot.extend(fresh);
				}
				stats.updated += 1;
			}
			_ => {
				existing.push(task);
				stats.added += 1;
			}
		}
	}
	stats
}

// ---- files

/// An existing JSON document and the indentation it uses, or nothing.
fn read_json(path: &Path) -> Result<(Option<Value>, String), String> {
	let Ok(text) = std::fs::read_to_string(path) else {
		return Ok((None, DEFAULT_INDENT.to_string()));
	};
	let value: Value = serde_json::from_str(&text)
		.map_err(|e| format!("{}: not valid JSON ({e}); not touching it", path.display()))?;
	// The first indented line says what the file uses; a new file gets the
	// default. A JSON string cannot hold a raw newline, so a line's leading
	// whitespace is always structural.
	let indent = text
		.lines()
		.find(|l| l.starts_with(' ') || l.starts_with('\t'))
		.map(|l| l[..l.len() - l.trim_start().len()].to_string())
		.unwrap_or_else(|| DEFAULT_INDENT.to_string());
	Ok((Some(value), indent))
}

/// Pretty JSON at the given indentation, with a trailing newline.
fn render(v: &Value, indent: &str) -> String {
	let two = serde_json::to_string_pretty(v).expect("serializable");
	let mut out = String::with_capacity(two.len());
	for line in two.lines() {
		let lead = line.len() - line.trim_start().len();
		for _ in 0..lead / 2 {
			out.push_str(indent);
		}
		out.push_str(&line[lead..]);
		out.push('\n');
	}
	out
}

fn write(path: &Path, text: &str) -> Result<(), String> {
	if let Some(d) = path.parent() {
		std::fs::create_dir_all(d).map_err(|e| format!("{}: {e}", d.display()))?;
	}
	std::fs::write(path, text).map_err(|e| format!("{}: {e}", path.display()))
}

fn shown(root: &Path, path: &Path) -> String {
	path.strip_prefix(root)
		.unwrap_or(path)
		.display()
		.to_string()
		.replace('\\', "/")
}

// ---- zed

fn zed_task(e: &Entry) -> Value {
	let mut args = vec![json!("--stdin-args"), json!(e.name)];
	if e.uses_args {
		args.push(json!("$ZED_CUSTOM_ARGS"));
	}
	let mut t = Map::new();
	t.insert("label".into(), json!(label(&e.name)));
	t.insert("command".into(), json!("run"));
	t.insert("args".into(), Value::Array(args));
	t.insert("cwd".into(), json!("$ZED_WORKTREE_ROOT"));
	if e.uses_args {
		t.insert("allow_concurrent_runs".into(), json!(true));
	}
	Value::Object(t)
}

fn zed(entries: &[Entry], root: &Path, opts: &Options) -> Result<String, String> {
	let generated: Vec<Value> = entries.iter().map(zed_task).collect();
	if opts.stdout {
		print!("{}", render(&Value::Array(generated), DEFAULT_INDENT));
		return Ok(String::new());
	}
	let path = root.join(".zed").join("tasks.json");
	let (existing, indent) = read_json(&path)?;
	let mut tasks = match existing {
		Some(Value::Array(a)) => a,
		Some(_) => return Err(format!("{}: expected a JSON array of tasks", path.display())),
		None => Vec::new(),
	};
	let stats = merge(&mut tasks, generated);
	write(&path, &render(&Value::Array(tasks), &indent))?;
	Ok(format!("{}: {stats}", shown(root, &path)))
}

// ---- vscode

fn vscode_task(e: &Entry) -> Value {
	let mut args = vec![json!("--stdin-args"), json!(e.name)];
	if e.uses_args {
		args.push(json!("${input:args}"));
	}
	let mut t = Map::new();
	t.insert("label".into(), json!(label(&e.name)));
	t.insert("type".into(), json!("shell"));
	t.insert("command".into(), json!("run"));
	t.insert("args".into(), Value::Array(args));
	if !e.description.is_empty() {
		t.insert("detail".into(), json!(e.description));
	}
	t.insert("presentation".into(), json!({"reveal": "always", "panel": "shared"}));
	Value::Object(t)
}

fn vscode(entries: &[Entry], root: &Path, opts: &Options) -> Result<String, String> {
	let generated: Vec<Value> = entries.iter().map(vscode_task).collect();
	let prompts = entries.iter().any(|e| e.uses_args);
	let path = root.join(".vscode").join("tasks.json");
	let (existing, indent) = if opts.stdout {
		(None, DEFAULT_INDENT.to_string())
	} else {
		read_json(&path)?
	};
	let mut file = match existing {
		Some(Value::Object(o)) => o,
		Some(_) => return Err(format!("{}: expected a JSON object", path.display())),
		None => Map::new(),
	};
	file.entry("version").or_insert(json!("2.0.0"));
	let mut tasks = match file.remove("tasks") {
		Some(Value::Array(a)) => a,
		_ => Vec::new(),
	};
	let stats = merge(&mut tasks, generated);
	file.insert("tasks".into(), Value::Array(tasks));
	// `${input:args}` needs a declared input; add ours only if no `args`
	// input exists, so a customised prompt is kept.
	if prompts {
		let inputs = file.entry("inputs").or_insert_with(|| Value::Array(Vec::new()));
		if let Value::Array(list) = inputs
			&& !list.iter().any(|i| i["id"] == "args")
		{
			list.push(json!({
				"id": "args",
				"type": "promptString",
				"description": "Arguments for run (leave empty for none)",
			}));
		}
	}
	let text = render(&Value::Object(file), &indent);
	if opts.stdout {
		print!("{text}");
		return Ok(String::new());
	}
	write(&path, &text)?;
	Ok(format!("{}: {stats}", shown(root, &path)))
}

// ---- jetbrains

fn xml_attr(s: &str) -> String {
	let mut out = String::with_capacity(s.len());
	for c in s.chars() {
		match c {
			'&' => out.push_str("&amp;"),
			'<' => out.push_str("&lt;"),
			'>' => out.push_str("&gt;"),
			'"' => out.push_str("&quot;"),
			'\'' => out.push_str("&apos;"),
			c => out.push(c),
		}
	}
	out
}

/// `api:deploy` -> `Api Deploy`, the way run configurations are named.
fn pretty(name: &str) -> String {
	name.split(|c: char| !c.is_alphanumeric())
		.filter(|w| !w.is_empty())
		.map(|w| {
			let mut cs = w.chars();
			match cs.next() {
				Some(f) => f.to_uppercase().chain(cs).collect::<String>(),
				None => String::new(),
			}
		})
		.collect::<Vec<_>>()
		.join(" ")
}

fn config_file(name: &str) -> String {
	let safe: String = name
		.chars()
		.map(|c| if c.is_alphanumeric() { c } else { '_' })
		.collect();
	format!("Runfile_{safe}.run.xml")
}

fn jetbrains_config(e: &Entry) -> String {
	let (name, target) = (xml_attr(&pretty(&e.name)), xml_attr(&e.name));
	format!(
		r#"<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="{name}" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run --stdin-args {target}" />
    <option name="INDEPENDENT_SCRIPT_PATH" value="true" />
    <option name="SCRIPT_PATH" value="" />
    <option name="SCRIPT_OPTIONS" value="" />
    <option name="INDEPENDENT_SCRIPT_WORKING_DIRECTORY" value="true" />
    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
    <option name="INDEPENDENT_INTERPRETER_PATH" value="true" />
    <option name="INTERPRETER_PATH" value="" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="EXECUTE_IN_TERMINAL" value="false" />
    <option name="EXECUTE_SCRIPT_FILE" value="false" />
    <envs />
    <method v="2" />
  </configuration>
</component>
"#
	)
}

/// A configuration is ours if it runs `run --stdin-args <target>` from the
/// project directory; the target it names is what a stale one is checked by.
fn jetbrains_target_of(contents: &str) -> Option<String> {
	if !contents.contains(r#"type="ShConfigurationType""#)
		|| !contents.contains(r#"name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$""#)
	{
		return None;
	}
	let rest = contents
		.split(r#"name="SCRIPT_TEXT" value="run --stdin-args "#)
		.nth(1)?;
	Some(rest.split('"').next()?.to_string())
}

fn jetbrains(entries: &[Entry], root: &Path, opts: &Options) -> Result<String, String> {
	let dir = root.join(".idea").join("runConfigurations");
	if opts.stdout {
		for e in entries {
			print!(
				"<!-- {}/{} -->\n{}",
				shown(root, &dir),
				config_file(&e.name),
				jetbrains_config(e)
			);
		}
		return Ok(String::new());
	}
	let mut stats = Stats::default();
	let wanted: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();

	// Stale configurations of ours go first, so a renamed target does not
	// leave its old name behind.
	if let Ok(existing) = std::fs::read_dir(&dir) {
		for f in existing.flatten() {
			let name = f.file_name().to_string_lossy().to_string();
			if !name.starts_with("Runfile_") || !name.ends_with(".run.xml") {
				continue;
			}
			let Ok(text) = std::fs::read_to_string(f.path()) else {
				continue;
			};
			if let Some(target) = jetbrains_target_of(&text)
				&& !wanted.contains(&target.as_str())
			{
				std::fs::remove_file(f.path()).map_err(|e| format!("{}: {e}", f.path().display()))?;
				stats.removed += 1;
			}
		}
	}
	for e in entries {
		let path = dir.join(config_file(&e.name));
		let fresh = jetbrains_config(e);
		match std::fs::read_to_string(&path) {
			Ok(old) if jetbrains_target_of(&old).is_none() => {
				stats.skipped.push(shown(root, &path));
			}
			Ok(old) if old == fresh => {}
			Ok(_) => {
				write(&path, &fresh)?;
				stats.updated += 1;
			}
			Err(_) => {
				write(&path, &fresh)?;
				stats.added += 1;
			}
		}
	}
	Ok(format!("{}/: {stats}", shown(root, &dir)))
}

#[cfg(test)]
mod tests {
	use super::*;

	fn task(label: &str, command: &str, args: &[&str]) -> Value {
		json!({"label": label, "command": command, "args": args})
	}

	#[test]
	fn an_entry_is_ours_by_shape_not_by_marker() {
		assert!(ours(&task("run build", "run", &["--stdin-args", "build"])));
		assert!(
			ours(&task("run build", "run", &["build"])),
			"the older shape counts too"
		);
		assert!(!ours(&task("run build", "make", &["build"])), "another command");
		assert!(!ours(&task("Build", "run", &["build"])), "another label");
		assert!(!ours(&task("run build", "run", &["test"])), "label and args disagree");
	}

	#[test]
	fn merge_replaces_ours_and_keeps_theirs() {
		let mut existing = vec![
			task("run old", "run", &["--stdin-args", "old"]),
			task("run build", "run", &["build"]),
			json!({"label": "lint everything", "command": "make", "args": ["lint"]}),
		];
		let stats = merge(
			&mut existing,
			vec![
				task("run build", "run", &["--stdin-args", "build"]),
				task("run test", "run", &["--stdin-args", "test"]),
			],
		);
		assert_eq!((stats.added, stats.updated, stats.removed), (1, 1, 1));
		let labels: Vec<&str> = existing.iter().map(|t| t["label"].as_str().unwrap()).collect();
		assert_eq!(labels, ["run build", "lint everything", "run test"]);
		assert_eq!(existing[0]["args"][0], "--stdin-args", "updated in place");
	}

	#[test]
	fn merge_keeps_extra_keys_a_person_added_to_our_entry() {
		let mut existing = vec![json!({"label": "run build", "command": "run", "args": ["build"], "reveal": "never"})];
		merge(
			&mut existing,
			vec![task("run build", "run", &["--stdin-args", "build"])],
		);
		assert_eq!(existing[0]["reveal"], "never");
	}

	#[test]
	fn render_uses_the_requested_indentation() {
		let v = json!({"a": [1, {"b": 2}]});
		let tabs = render(&v, "\t");
		assert!(tabs.contains("\n\t\"a\": [\n\t\t1,\n\t\t{\n\t\t\t\"b\": 2"), "{tabs}");
		assert!(tabs.ends_with("}\n"));
		let four = render(&v, "    ");
		assert!(four.contains("\n    \"a\""), "{four}");
	}

	#[test]
	fn a_jetbrains_configuration_names_its_target_and_is_recognised() {
		let e = Entry {
			name: "api:deploy".into(),
			description: String::new(),
			uses_args: false,
		};
		let xml = jetbrains_config(&e);
		assert!(xml.contains(r#"name="Api Deploy""#), "{xml}");
		assert!(xml.contains(r#"value="run --stdin-args api:deploy""#), "{xml}");
		assert_eq!(jetbrains_target_of(&xml).as_deref(), Some("api:deploy"));
		assert!(
			jetbrains_target_of("<component/>").is_none(),
			"a foreign file is not ours"
		);
		assert_eq!(config_file("api:deploy"), "Runfile_api_deploy.run.xml");
	}

	#[test]
	fn xml_attributes_are_escaped() {
		assert_eq!(xml_attr(r#"a<b>&"c'"#), "a&lt;b&gt;&amp;&quot;c&apos;");
	}
}
